# This file was generated by the {rix} R package v0.17.2 on 2025-12-11
# with following call:
# >rix(date = "2025-08-25",
#  > r_pkgs = c("rix",
#  > "quarto",
#  > "knitr",
#  > "marginaleffects",
#  > "simhelpers",
#  > "ggplot2",
#  > "doParallel",
#  > "doRNG",
#  > "cowplot",
#  > "dplyr"),
#  > system_pkgs = c("quarto"),
#  > tex_pkgs = c("amsmath",
#  > "ninecolors",
#  > "apa7",
#  > "scalerel",
#  > "threeparttable",
#  > "threeparttablex",
#  > "endfloat",
#  > "environ",
#  > "multirow",
#  > "tcolorbox",
#  > "pdfcol",
#  > "tikzfill",
#  > "fontawesome5",
#  > "framed",
#  > "newtx",
#  > "fontaxes",
#  > "xstring",
#  > "wrapfig",
#  > "tabularray",
#  > "siunitx",
#  > "fvextra",
#  > "geometry",
#  > "setspace",
#  > "fancyvrb",
#  > "anyfontsize"),
#  > ide = "rstudio",
#  >      project_path = ".",
#  > overwrite = TRUE,
#  > r_ver = "4.5.1")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2025-08-25.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      cowplot
      doParallel
      doRNG
      dplyr
      ggplot2
      knitr
      marginaleffects
      quarto
      rix
      simhelpers;
  };
  
  tex = (pkgs.texlive.combine {
    inherit (pkgs.texlive) 
      scheme-small
      amsmath
      anyfontsize
      apa7
      endfloat
      environ
      fancyvrb
      fontawesome5
      fontaxes
      framed
      fvextra
      geometry
      multirow
      newtx
      ninecolors
      pdfcol
      scalerel
      setspace
      siunitx
      tabularray
      tcolorbox
      threeparttable
      threeparttablex
      tikzfill
      wrapfig
      xstring;
  });
    
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      quarto
      R
      which
      pandoc;
  };
 
  wrapped_pkgs = pkgs.rstudioWrapper.override {
    packages = [  rpkgs  ];
  };
 
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ rpkgs tex system_packages wrapped_pkgs ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
